project_name: fing

before:
  hooks:
    - go mod tidy
    - go generate ./...


builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
    ldflags:
      - -X github.com/fingcloud/cli/internal/cli.BuildDate={{ .Date }}
      - -X github.com/fingcloud/cli/internal/cli.Version={{ .Version }}
      - -X github.com/fingcloud/cli/internal/cli.Commit={{ .ShortCommit }}

archives:
  - name_template: "fing-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files: [a-workaround-to-include-only-the-binary*]
    wrap_in_directory: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - tap:
      owner: fingcloud
      name: homebrew-tap
    folder: Formula
    homepage: https://fing.ir
    skip_upload: auto
    test: |
      system "#{bin}/fing version"
    install: |
      bin.install "fing"

dockers:
  - goos: linux
    goarch: amd64
    skip_push: auto
    image_templates:
    - "fingcloud/cli:latest"
    - "fingcloud/cli:{{ .Version }}"

release:
  github:
    owner: fingcloud
    name: cli

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^deps:"
      - "^wip:"
